import { escape } from '../../scripts/content.mjs';
export const brand = `<a class="brand" href="/" aria-label="Makex India home"><img src="/Makex_green.svg" width="42" height="44" alt=""><span>MAKE<span class="brand-x">X</span><small>INDIA</small></span></a>`;
export function header(site, pagePath='/') {
  return `<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="wrap header-inner">${brand}
<div class="header-controls"><button class="theme-toggle icon-button" type="button" hidden aria-label="Switch to dark theme"><svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M12 4a8 8 0 0 1 0 16Z" fill="currentColor"/></svg></button>
<button class="menu-toggle" type="button" hidden aria-expanded="false" aria-controls="primary-nav">Menu <span aria-hidden="true">☰</span></button></div>
<nav id="primary-nav" aria-label="Primary"><a href="/ideas/"${pagePath==='/ideas/'?' aria-current="page"':''}>Ideas</a><a href="/#builds">Builds</a><a href="/#approach">Approach</a><a href="/#people">People</a><a href="${site.writing}">Writing <span aria-hidden="true">↗</span></a><a class="button button-small" href="/#contact">Share an Idea <span aria-hidden="true">↗</span></a></nav>
</div></header>`;
}
export function base({site, body, footer, theme, cssHash, jsHash, readingCssHash, page={}}) {
  const path=page.path||'/', title=page.title||site.title, description=page.description||site.description;
  const socialTitle=page.socialTitle||page.title||'Makex India — Technology for Things That Should Work Better';
  const canonical=site.origin+path;
  const schema = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'Organization', '@id': `${site.origin}/#organization`, name: 'Makex India', url: `${site.origin}/`, logo: `${site.origin}/Makex_green.svg`, description: site.description,
      sameAs: ['https://www.linkedin.com/company/makexindia', site.github, 'https://www.youtube.com/@makexindia'] },
    { '@type': 'WebSite', '@id': `${site.origin}/#website`, url: `${site.origin}/`, name: 'Makex India', publisher: { '@id': `${site.origin}/#organization` }, inLanguage: 'en' }
  ] };
  if(page.article) schema['@graph'].push({ '@type':'Article', headline:page.article.title, description,
    mainEntityOfPage:canonical, publisher:{'@id':`${site.origin}/#organization`},
    author:{'@id':`${site.origin}/#organization`}, inLanguage:'en' });
  return `<!doctype html>
<!-- Generated by npm run build. Edit src/, not this file. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark"><script>${theme}</script>
<title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${canonical}">
<meta property="og:type" content="${page.article?'article':'website'}"><meta property="og:url" content="${canonical}"><meta property="og:title" content="${escape(socialTitle)}"><meta property="og:description" content="${escape(description)}"><meta property="og:image" content="${site.origin}/assets/social/makex-og.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Makex India. Technology for things that should work better.">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(socialTitle)}"><meta name="twitter:description" content="${escape(description)}"><meta name="twitter:image" content="${site.origin}/assets/social/makex-og.png">
<meta name="theme-color" content="#f8faf9" media="(prefers-color-scheme: light)"><meta name="theme-color" content="#0d1512" media="(prefers-color-scheme: dark)">
<link rel="icon" href="/favicon.ico"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="manifest" href="/site.webmanifest">
<link rel="stylesheet" href="/assets/site.css?v=${cssHash}">${readingCssHash?`<link rel="stylesheet" href="/assets/reading.css?v=${readingCssHash}">`:''}<script src="/assets/site.js?v=${jsHash}" defer></script>
<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<', '\\u003c')}</script>
</head><body>${header(site,path)}<main id="main" tabindex="-1">${body}</main>${footer}</body></html>\n`;
}
